### ISSUE TITLE
продублировать ссылки

### ISSUE THREAD

**Issue by dimikras** [SergeyPensov/mainIssues#15]
На сайте ссылки которые есть на верху т.е. 
Главная, О проекте, Правила, Инструкция, Онлайн Кошелек, Скачать, Статистика, Форум

так же продублировать внизу там сейчас только 
О проекте, Онлайн Кошелек, Скачать, Форум

**Comment by SergeyPensov** [comment]
Я специально не добавлял, так как оно теряет внешний вид и портит юзабилити
