### ISSUE TITLE
Транзакция (перевод монет) не проходит и кредиты за суппорт и форджинг не получаю. Опять та же проблема(((

### ISSUE THREAD

**Issue by dimikras** [SergeyPensov/mainIssues#16]
Пару дней назад, Антон мне жаловался на то что его знакомый опять имел проблему с тем что его компьютер терял связь с нетворком. 
Вчера он мне уже говорил что и у него была такая проблема. 
Сегодня и у меня возникла проблема что я вижу нетворк, блоки идут а транзакция (перевод монет) с моего аккаунта не проходит. Транзакция на экране то исчезает то появляется опять но она не проходит. 
Кредиты за суппорт и форджинг я не получаю.

**Comment by SergeyPensov** [comment]
Я тогда сейчас займусь же этой проблемой. Я сделаю систму, как я и рассказывал. И попытаюсь найти Jprofilerб что бы прогнать его у меня и желательно на одной из супер нод с виндой.
Кредиты вы перестаете получать, так как никто не знает, что вы в сети(вы потеряли конекшн)
