### ISSUE TITLE
сделать ссылки вверх обратно к оглавлению

### ISSUE THREAD

**Issue by dimikras** [SergeyPensov/mainIssues#18]
На странице инструкция http://ecoin.zone/instruction.html, 
после каждого пункта сделать ссылки вверх обратно к оглавлению

**Comment by SergeyPensov** [comment]
Я этим займусь как можно скорее.Вы не заливали новый текст?

**Comment by dimikras** [comment]
Заливал, я добавил 3 фотки и редактировал ru и instruction
