### ISSUE TITLE
вопрос по редактированию страниц

### ISSUE THREAD

**Issue by dimikras** [SergeyPensov/mainIssues#3]
Можно ли редактировать текст локально что бы результат видеть у себя на компьютере а потом когда я убедился что всё ОК делать аплоуд на сервер?

**Comment by SergeyPensov** [comment]
Да. Для этого скачайте с продакш-сервера папку с HTML и замените её у себя. Вы получите последнюю версию страниц сайта и после этого проделываете всё, что я вам показывал в офисе.

**Comment by dimikras** [comment]
я скопировал папку, но у меня появляются только картинки а текст не появляется
