### ISSUE TITLE
кредиты за суппорт через Postman

### ISSUE THREAD

**Issue by dimikras** [SergeyPensov/mainIssues#38]
Можно ли запустить суппорт через хромовского Postman? 
Я попробовал запустить аккаунт, но запустился только форджинг, а суппорт нет.

http://54.93.199.151:7878/ecn?requestType=startForging&secretPhrase=dima7

может можно как то это делать по другому?

**Comment by SergeyPensov** [comment]
http://localhost:7878/ecn?requestType=makeAccountMain&secretPhrase=openfaces&account=18078597922978282671

Это должно решить вашу проблему
