### ISSUE TITLE
Genesis Blocks History показывает одну и туже информацию и количество аккаунтов иногда показывает в разы больше чем есть

### ISSUE THREAD

**Issue by dimikras** [SergeyPensov/mainIssues#43]
Genesis Blocks History показывает одну и туже информацию и количество аккаунтов иногда показывает в разы больше чем есть

![genblockhist](https://cloud.githubusercontent.com/assets/11174418/6770979/a7e7210a-d0d9-11e4-8c9c-138bf0667c5e.png)

**Comment by SergeyPensov** [comment]
заметка
Количество аккаунтов увеличиваеться в геометрической последовательности
