### ISSUE TITLE
Как может получится что бы количество добавленных % транзакционных монет УМЕНьШИЛОСь от блока 1289 к блоку 1294  т.е. добавилось до 00050964 а потом уменьшилось до 0003265 скрин прилагаю

### ISSUE THREAD

**Issue by dimikras** [SergeyPensov/mainIssues#52]
Как может получится что бы количество добавленных в % транзакционных монет УМЕНьШИЛОСь от блока 1289 к блоку 1294 
т.е. добавилось до 00050964
а потом уменьшилось до 0003265
скрин прилагаю

![totaltrans](https://cloud.githubusercontent.com/assets/11174418/6984883/73ff7510-d9fb-11e4-81c1-501d286d6795.png)

**Comment by SergeyPensov** [comment]
Как я говориЛ. мне нужна база, что бы проверить математику.Так причин обьективных не вижу
