### ISSUE TITLE
Создать функционал для обмена намайненых монет на икоин

### ISSUE THREAD

**Issue by dimikras** [SergeyPensov/mainIssues#71]
Функционал при котором админ сможет распределить монеты икоин пропорционально между участниками участвовавшими в майненге соответствующей валюты за период с предыдущей продажи

**Comment by SergeyPensov** [comment]
Добавить панель админа для раздачи денег и сделать привликательной форму просмотра статистики для пользователей + добавить линк на основной сайт для просмтра статистики пользователями
